name: Lint

on:
  push:

    branches: ["*"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Check Python files
        run: |
          python -m py_compile plot_axes_scores.py plot_eladeb.py

      - name: Check JavaScript syntax
        run: |
          node --check src/main.js
          node --check src/ui.js
          node --check src/state.js
          node --check src/charts.js

      - name: Validate HTML
        run: |
          npx htmlhint index.html
        continue-on-error: true

